aws:
  bucket:
    access_key_id: AKIA2ODYHKQAIAKDNPJT
    secret_access_key: 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
    region: eu-central-1
    name: java-temp
    path: https://java-temp.s3.eu-central-1.amazonaws.com/
server:
  port: 9000
  error:
    include-message: always